# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  0 23 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Update paper list
        run: |
          cd paper_infos
          python generate_tables.py

      - name: Checkin
        run: |
          weixin0.exe 


      - name: Run a one-line script
        run: echo Hello, world!

