# This is a basic workflow to help you get started with Actions

name: 微信推送

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
        
      - name: requestss
        run:
         pip3 install requests
        
      - name: Update paper list
        run: |
          cd tuisong
          python main.py

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

