# This is a basic workflow to help you get started with Actions

name: 微信推送

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '1 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          
      - name: requests
        run:
          pip3 install requests
        
      - name: Update paper list
        run: |
          cd tuisong
          python main.py
